import os
import random
import requests
import subprocess

GITHUB_RAW = "https://raw.githubusercontent.com/yasukomatsuyuki0904-tech/animalhero-ffmpeg/main/BGM"

TENSION_BGM = [
    {"file": "Duty Calls - Rod Kim.mp3",                        "start": "00:00:00", "duration": "10"},
    {"file": "Frodo's Quest - Ezra Lipp.mp3",                   "start": "00:00:00", "duration": "10"},
    {"file": "The Marble Cinematic University - Ezra Lipp.mp3", "start": "00:01:07", "duration": "10"},
    {"file": "The Road To Mordor - Ezra Lipp.mp3",              "start": "00:00:07", "duration": "10"},
]

WARM_BGM = [
    {"file": "Alpine Bierhalle - Aaron Kenny.mp3",              "start": "00:00:11", "duration": "5"},
    {"file": "Everything Has a Beginning - Joel Cummins.mp3",   "start": "00:00:00", "duration": "5"},
    {"file": "Fiesta de la Vida - Aaron Kenny.mp3",             "start": "00:01:24", "duration": "5"},
    {"file": "Gaiety in the Golden Age - Aaron Kenny.mp3",      "start": "00:01:44", "duration": "5"},
]

# warm mood 時需要10秒版本的 warm BGM 當主軌
WARM_BGM_LONG = [
    {"file": "Alpine Bierhalle - Aaron Kenny.mp3",              "start": "00:00:11", "duration": "10"},
    {"file": "Everything Has a Beginning - Joel Cummins.mp3",   "start": "00:00:00", "duration": "10"},
    {"file": "Fiesta de la Vida - Aaron Kenny.mp3",             "start": "00:01:24", "duration": "10"},
    {"file": "Gaiety in the Golden Age - Aaron Kenny.mp3",      "start": "00:01:44", "duration": "10"},
]

# tension mood 時需要5秒版本的 tension BGM 當副軌
TENSION_BGM_SHORT = [
    {"file": "Duty Calls - Rod Kim.mp3",                        "start": "00:00:00", "duration": "5"},
    {"file": "Frodo's Quest - Ezra Lipp.mp3",                   "start": "00:00:00", "duration": "5"},
    {"file": "The Marble Cinematic University - Ezra Lipp.mp3", "start": "00:01:07", "duration": "5"},
    {"file": "The Road To Mordor - Ezra Lipp.mp3",              "start": "00:00:07", "duration": "5"},
]


def download_file(url, output_path):
    headers = {'User-Agent': 'Mozilla/5.0'}
    session = requests.Session()
    r = session.get(url, stream=True, allow_redirects=True, headers=headers)
    r.raise_for_status()
    with open(output_path, 'wb') as f:
        for chunk in r.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)


def create_release_and_upload(mp4_path, run_id, token, repo):
    """建立 GitHub Release 並上傳 mp4，回傳下載 URL"""
    tag = f"run-{run_id}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    # 建立 Release
    print(f"Creating release with tag {tag}")
    r = requests.post(
        f"https://api.github.com/repos/{repo}/releases",
        headers=headers,
        json={
            "tag_name": tag,
            "name": f"AnimalHero Output {run_id}",
            "body": "Auto-generated by AnimalHero pipeline",
            "draft": False,
            "prerelease": False,
        }
    )
    r.raise_for_status()
    release = r.json()
    upload_url = release["upload_url"].replace("{?name,label}", "")
    release_id = release["id"]

    # 上傳 mp4
    print(f"Uploading output.mp4 to release {release_id}")
    with open(mp4_path, 'rb') as f:
        upload_headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "video/mp4",
        }
        r2 = requests.post(
            f"{upload_url}?name=output.mp4",
            headers=upload_headers,
            data=f
        )
        r2.raise_for_status()
        asset = r2.json()

    mp4_url = asset["browser_download_url"]
    print(f"MP4 URL: {mp4_url}")
    return mp4_url


def main():
    video_url_1  = os.environ['VIDEO_URL_1']
    video_url_2  = os.environ['VIDEO_URL_2']
    video_url_3  = os.environ['VIDEO_URL_3']
    webhook_url  = os.environ['WEBHOOK_URL']
    mood         = os.environ.get('MOOD', 'tension')
    run_id       = os.environ['GITHUB_RUN_ID']
    token        = os.environ['GITHUB_TOKEN']
    repo         = os.environ['GITHUB_REPOSITORY']

    # 根據 mood 決定主軌（10秒）和副軌（5秒）
    if mood == 'warm':
        bgm_main = random.choice(WARM_BGM_LONG)   # warm 10秒 主軌
        bgm_sub  = random.choice(TENSION_BGM_SHORT) # tension 5秒 副軌
    else:
        bgm_main = random.choice(TENSION_BGM)      # tension 10秒 主軌
        bgm_sub  = random.choice(WARM_BGM)         # warm 5秒 副軌

    print(f"Mood:     {mood}")
    print(f"Main BGM: {bgm_main['file']} ({bgm_main['duration']}s)")
    print(f"Sub BGM:  {bgm_sub['file']} ({bgm_sub['duration']}s)")

    # 下載三段影片
    for i, url in enumerate([video_url_1, video_url_2, video_url_3], 1):
        print(f"Downloading video {i} from {url}")
        download_file(url, f"input_video_{i}.mp4")

    # 下載 BGM
    main_url = f"{GITHUB_RAW}/{requests.utils.quote(bgm_main['file'])}"
    sub_url  = f"{GITHUB_RAW}/{requests.utils.quote(bgm_sub['file'])}"
    download_file(main_url, "bgm_main.mp3")
    download_file(sub_url,  "bgm_sub.mp3")

    # Step 1: 串接三段影片
    with open("concat_list.txt", 'w') as f:
        for i in range(1, 4):
            f.write(f"file 'input_video_{i}.mp4'\n")
    subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0",
                    "-i", "concat_list.txt", "-c", "copy", "merged_video.mp4"], check=True)

    # Step 2: 裁切主軌 BGM（10秒）
    subprocess.run(["ffmpeg", "-y", "-ss", bgm_main["start"], "-t", bgm_main["duration"],
                    "-i", "bgm_main.mp3", "-c:a", "aac", "-b:a", "128k", "main_trim.aac"], check=True)

    # Step 3: 裁切副軌 BGM（5秒）
    subprocess.run(["ffmpeg", "-y", "-ss", bgm_sub["start"], "-t", bgm_sub["duration"],
                    "-i", "bgm_sub.mp3", "-c:a", "aac", "-b:a", "128k", "sub_trim.aac"], check=True)

    # Step 4: 拼接 BGM（主軌 + 副軌）
    with open("bgm_list.txt", 'w') as f:
        f.write("file 'main_trim.aac'\n")
        f.write("file 'sub_trim.aac'\n")
    subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0",
                    "-i", "bgm_list.txt", "-c", "copy", "full_bgm.aac"], check=True)

    # Step 5: 合併影片 + BGM
    subprocess.run(["ffmpeg", "-y", "-i", "merged_video.mp4", "-i", "full_bgm.aac",
                    "-map", "0:v", "-map", "1:a", "-c:v", "copy", "-c:a", "aac",
                    "-shortest", "output.mp4"], check=True)

    print("Done: output.mp4")

    # Step 6: 上傳到 GitHub Release 取得 mp4 URL
    mp4_url = create_release_and_upload("output.mp4", run_id, token, repo)

    # Step 7: 通知 V10C
    print(f"Notifying webhook: {webhook_url}")
    requests.post(webhook_url, json={"status": "done", "mp4_url": mp4_url})


if __name__ == '__main__':
    main()
